---
- name: "user"
  user:
    home: "{{ dogecoin.user.home_folder }}"
    name: "{{ dogecoin.user.name }}"
    state: "present"

- name: "copy binary"
  copy:
    src: "{{ dogecoin.binary_src }}"
    dest: "{{ dogecoin.user.home_folder }}"

- name: "make dogecoin dir"
  file:
    state: "directory"
    path: "{{ dogecoin.user.home_folder }}/.dogecoin"

- name: "conf"
  template:
    src: "dogecoin.tmpl.conf"
    dest: "{{ dogecoin.user.home_folder }}/.dogecoin/dogecoin.conf"

- name: "chown user dir"
  shell: "chown -R {{ dogecoin.user.name }}:{{ dogecoin.user.name }} {{ dogecoin.user.home_folder }}"

- name: "chmod user dir"
  shell: "chmod -R 700 {{ dogecoin.user.home_folder }}"

- name: "upstart script"
  template:
    src: "dogecoind.tmpl.conf"
    dest: "/etc/init/dogecoind.conf"

- name: "start upstart"
  service:
    name: "dogecoind"
    state: "started"
    enabled: "yes"