---
- name: install psycopg2 # crappy python package management
  sudo: yes
  apt: pkg=python-psycopg2

- name: check database
  sudo: yes
  sudo_user: postgres
  postgresql_db: name={{ postgres.name }}

- name: check access
  sudo: yes
  sudo_user: postgres
  postgresql_user: db={{ postgres.name }} name={{ postgres.name }} password={{ postgres.password }} priv=ALL

- name: check privilege
  sudo: yes
  sudo_user: postgres
  postgresql_user: name={{ postgres.name }} role_attr_flags=NOSUPERUSER,NOCREATEDB