---
- name: user
  user:
    home: "{{ app.user.home_folder }}"
    name: "{{ app.user.name }}"
    state: "present"

- name: "synchronize source"
  synchronize:
    src: "../../../../" # get source dir
    dest: "{{ app.user.home_folder }}/{{ app.name }}"

- name: "template config file"
  template:
    src: config.tmpl.js
    dest: "{{ app.user.home_folder }}/{{ app.name }}/config/config.js"

- name: "migrate db"
  shell: "node {{ app.user.home_folder }}/{{ app.name }}/migrations/migrate.js 001 >> /migration_log 2>&1"


- name: "chown user dir"
  shell: "chown -R {{ app.user.name }}:{{ app.user.name }} {{ app.user.home_folder }}"

- name: "chmod user dir"
  shell: "chmod -R 500 {{ app.user.home_folder }}"


- name: "build frontend"
  command: >
    node_modules/.bin/gulp build
    chdir={{ app.user.home_folder }}/{{ app.name }}


- name: 'copy static files'
  shell: "mv /{{ app.user.home_folder }}/{{ app.name }}/static/ /home/nginx/static/"

- name: "chown static dir"
  shell: "chown -R www-data:www-data /home/nginx/static/"

- name: "chmod static dir"
  shell: "chmod -R 400 /home/nginx/static/"


- name: "upstart script"
  template:
    src: "{{ app.name }}.tmpl.conf"
    dest: "/etc/init/{{ app.name }}.conf"

- name: "start upstart"
  service:
    name: "{{ app.name }}"
    state: "started"
    enabled: "yes"