---
- name: user
  user:
    home: "{{ app.user.home_folder }}"
    name: "{{ app.user.name }}"
    state: "present"

- name: "synchronize source"
  synchronize:
    src: "../../../../" # get source dir
    dest: "{{ app.user.home_folder }}/{{ app.name }}"

- name: "template config file"
  template:
    src: config.tmpl.js
    dest: "{{ app.user.home_folder }}/{{ app.name }}/config/config.js"

- name: "chown user dir"
  shell: "chown -R {{ app.user.name }}:{{ app.user.name }} {{ app.user.home_folder }}"

- name: "chmod user dir"
  shell: "chmod -R 700 {{ app.user.home_folder }}"

- name: "migrate db"
  shell: "node {{ app.user.home_folder }}/{{ app.name }}/migrations/migrate.js 001 >> /log_file 2>&1"

# - name: "install gulp"
#   npm:
#     name: "gulp"
#     path: "{{ app.user.home_folder }}/{{ app.name }}"

# - name: "build frontend"
#   shell: "node_modules/.bin/gulp build"

- name: "build frontend"
  command: >
    node_modules/.bin/gulp build
    chdir={{ app.user.home_folder }}/{{ app.name }}

- name: "upstart script"
  template:
    src: "{{ app.name }}.tmpl.conf"
    dest: "/etc/init/{{ app.name }}.conf"

- name: "start upstart"
  service:
    name: "{{ app.name }}"
    state: "started"
    enabled: "yes"