---
- hosts: production
  user: root
  vars_files:
    - secrets.yml
    - vars.yml

  roles:
    - app

  tasks:
    - name: "start dogecoind upstart"
      service:
        name: "dogecoind"
        state: "started"
        enabled: "yes"