---
ssl:
  vhost:
    hostname: dogewand.org
    port: 3700
  cert:
    certificate_src: dogewand.org.crt
    key_src: dogewand.org.protected.key
    certificate_dest: /etc/ssl/certs/dogewand.org.crt
    key_dest: /etc/ssl/private/dogewand.org.protected.key
    key_stripped: /etc/ssl/private/dogewand.org.key

app:
  name: dogewand
  logs: /var/log/dogewand/sys.log
  user:
    name: dogewanduser
    home_folder: /home/dogewanduser

dogecoin:
  binary_src: dogecoind
  rpc_password: dogecoind_password
  logs: /var/log/dogecoind/sys.log
  user:
    name: dogecoinuser
    home_folder: /home/dogecoinuser